### PR TITLE
remove Math.round

### PR DESCRIPTION
**Pull request by caohuilin**
image
  
Math.round Cause spacing problems

### CODE REVIEW

**Comment by Fil** [comment]
Can you share the code that generates the broken graph?

**Comment by caohuilin** [comment]
https://github.com/caohuilin/honeycomb-chart

- npm install
- npm start
- cd example
- npm install
- npm start

**Comment by mbostock** [comment]
These Math.round are used to compute the integer indexes of the hexbin, i.e., to assign arbitrary real coordinates to a specific hexbin. Removing this rounding as proposed in this PR would make d3-hexbin not work at all.

The rendering artifacts from your screenshot must be coming from somewhere else. If you’re willing to give us a link to your code running on the web, I’d be happy to look further, but I’d rather not npm install and run arbitrary code without knowing who you are first. :)

**Comment by caohuilin** [comment]
https://codesandbox.io/s/damp-framework-6utlh?file=/src/index.js

**Comment by mbostock** [comment]
The problem is that you haven’t set *hexbin*.radius, so you’re getting the default radius of 1. This means that you have a very dense (gray) but sparsely-populated (black) hexbin grid. You’re then scaling up the radius of the populated hexbins to 9 (red), giving the false appearance of a coarse grid.

untitled (34)

If you fix the *hexbin*.radius to the desired radius, then you don’t need to pass this radius to *hexbin*.hexagon, and you’ll get the desired grid:

untitled (35)

https://observablehq.com/d/ad18dda18e01d469

**Comment by caohuilin** [comment]
Thanks, I resolve my problem

**Pull request closed without merging**
